package com.elearing.entity;
// Generated Jun 27, 2015 4:08:38 PM by Hibernate Tools 4.3.1



/**
 * ChapterImage generated by hbm2java
 */
public class ChapterImage  implements java.io.Serializable {


     private Integer chaImgId;
     private SubChapter subChapter;
     private String imageName;
     private String imageUrl;
     private String imageType;
     private String imageSize;

    public ChapterImage() {
    }

    public ChapterImage(SubChapter subChapter, String imageName, String imageUrl, String imageType, String imageSize) {
       this.subChapter = subChapter;
       this.imageName = imageName;
       this.imageUrl = imageUrl;
       this.imageType = imageType;
       this.imageSize = imageSize;
    }
   
    public Integer getChaImgId() {
        return this.chaImgId;
    }
    
    public void setChaImgId(Integer chaImgId) {
        this.chaImgId = chaImgId;
    }
    public SubChapter getSubChapter() {
        return this.subChapter;
    }
    
    public void setSubChapter(SubChapter subChapter) {
        this.subChapter = subChapter;
    }
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public String getImageType() {
        return this.imageType;
    }
    
    public void setImageType(String imageType) {
        this.imageType = imageType;
    }
    public String getImageSize() {
        return this.imageSize;
    }
    
    public void setImageSize(String imageSize) {
        this.imageSize = imageSize;
    }




}


