package com.elearing.entity;
// Generated Jun 27, 2015 4:08:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ChapterType generated by hbm2java
 */
public class ChapterType  implements java.io.Serializable {


     private Integer chTyId;
     private Subject subject;
     private String typeName;
     private Set mcqQueses = new HashSet(0);
     private Set examQuesLinks = new HashSet(0);

    public ChapterType() {
    }

	
    public ChapterType(String typeName) {
        this.typeName = typeName;
    }
    public ChapterType(Subject subject, String typeName, Set mcqQueses, Set examQuesLinks) {
       this.subject = subject;
       this.typeName = typeName;
       this.mcqQueses = mcqQueses;
       this.examQuesLinks = examQuesLinks;
    }
   
    public Integer getChTyId() {
        return this.chTyId;
    }
    
    public void setChTyId(Integer chTyId) {
        this.chTyId = chTyId;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public Set getMcqQueses() {
        return this.mcqQueses;
    }
    
    public void setMcqQueses(Set mcqQueses) {
        this.mcqQueses = mcqQueses;
    }
    public Set getExamQuesLinks() {
        return this.examQuesLinks;
    }
    
    public void setExamQuesLinks(Set examQuesLinks) {
        this.examQuesLinks = examQuesLinks;
    }




}


