package com.elearing.entity;
// Generated Jun 27, 2015 4:08:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DescQuesMeta generated by hbm2java
 */
public class DescQuesMeta  implements java.io.Serializable {


     private Integer descMetaId;
     private DescQues descQues;
     private String descQuCmnt;
     private String userId;
     private Date cmntTime;

    public DescQuesMeta() {
    }

    public DescQuesMeta(DescQues descQues, String descQuCmnt, String userId, Date cmntTime) {
       this.descQues = descQues;
       this.descQuCmnt = descQuCmnt;
       this.userId = userId;
       this.cmntTime = cmntTime;
    }
   
    public Integer getDescMetaId() {
        return this.descMetaId;
    }
    
    public void setDescMetaId(Integer descMetaId) {
        this.descMetaId = descMetaId;
    }
    public DescQues getDescQues() {
        return this.descQues;
    }
    
    public void setDescQues(DescQues descQues) {
        this.descQues = descQues;
    }
    public String getDescQuCmnt() {
        return this.descQuCmnt;
    }
    
    public void setDescQuCmnt(String descQuCmnt) {
        this.descQuCmnt = descQuCmnt;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Date getCmntTime() {
        return this.cmntTime;
    }
    
    public void setCmntTime(Date cmntTime) {
        this.cmntTime = cmntTime;
    }




}


