package com.elearing.entity;
// Generated Jun 27, 2015 4:08:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ExamResult generated by hbm2java
 */
public class ExamResult  implements java.io.Serializable {


     private Integer rsId;
     private Exam exam;
     private User user;
     private Date examDate;
     private Integer totalQues;
     private Integer marksObtained;

    public ExamResult() {
    }

    public ExamResult(Exam exam, User user, Date examDate, Integer totalQues, Integer marksObtained) {
       this.exam = exam;
       this.user = user;
       this.examDate = examDate;
       this.totalQues = totalQues;
       this.marksObtained = marksObtained;
    }
   
    public Integer getRsId() {
        return this.rsId;
    }
    
    public void setRsId(Integer rsId) {
        this.rsId = rsId;
    }
    public Exam getExam() {
        return this.exam;
    }
    
    public void setExam(Exam exam) {
        this.exam = exam;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getExamDate() {
        return this.examDate;
    }
    
    public void setExamDate(Date examDate) {
        this.examDate = examDate;
    }
    public Integer getTotalQues() {
        return this.totalQues;
    }
    
    public void setTotalQues(Integer totalQues) {
        this.totalQues = totalQues;
    }
    public Integer getMarksObtained() {
        return this.marksObtained;
    }
    
    public void setMarksObtained(Integer marksObtained) {
        this.marksObtained = marksObtained;
    }




}


