package com.elearing.entity;
// Generated Jun 27, 2015 4:08:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * McqQues generated by hbm2java
 */
public class McqQues  implements java.io.Serializable {


     private Integer mcqId;
     private ChapterType chapterType;
     private QuesLevel quesLevel;
     private SubChapter subChapter;
     private String user;
     private String mcqTitle;
     private String op1;
     private String op2;
     private String op3;
     private String op4;
     private String ansOp;
     private Integer mcqType;
     private Date mcqPubTime;

    public McqQues() {
    }

    public McqQues(ChapterType chapterType, QuesLevel quesLevel, SubChapter subChapter, String user, String mcqTitle, String op1, String op2, String op3, String op4, String ansOp, Integer mcqType, Date mcqPubTime) {
       this.chapterType = chapterType;
       this.quesLevel = quesLevel;
       this.subChapter = subChapter;
       this.user = user;
       this.mcqTitle = mcqTitle;
       this.op1 = op1;
       this.op2 = op2;
       this.op3 = op3;
       this.op4 = op4;
       this.ansOp = ansOp;
       this.mcqType = mcqType;
       this.mcqPubTime = mcqPubTime;
    }
   
    public Integer getMcqId() {
        return this.mcqId;
    }
    
    public void setMcqId(Integer mcqId) {
        this.mcqId = mcqId;
    }
    public ChapterType getChapterType() {
        return this.chapterType;
    }
    
    public void setChapterType(ChapterType chapterType) {
        this.chapterType = chapterType;
    }
    public QuesLevel getQuesLevel() {
        return this.quesLevel;
    }
    
    public void setQuesLevel(QuesLevel quesLevel) {
        this.quesLevel = quesLevel;
    }
    public SubChapter getSubChapter() {
        return this.subChapter;
    }
    
    public void setSubChapter(SubChapter subChapter) {
        this.subChapter = subChapter;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getMcqTitle() {
        return this.mcqTitle;
    }
    
    public void setMcqTitle(String mcqTitle) {
        this.mcqTitle = mcqTitle;
    }
    public String getOp1() {
        return this.op1;
    }
    
    public void setOp1(String op1) {
        this.op1 = op1;
    }
    public String getOp2() {
        return this.op2;
    }
    
    public void setOp2(String op2) {
        this.op2 = op2;
    }
    public String getOp3() {
        return this.op3;
    }
    
    public void setOp3(String op3) {
        this.op3 = op3;
    }
    public String getOp4() {
        return this.op4;
    }
    
    public void setOp4(String op4) {
        this.op4 = op4;
    }
    public String getAnsOp() {
        return this.ansOp;
    }
    
    public void setAnsOp(String ansOp) {
        this.ansOp = ansOp;
    }
    public Integer getMcqType() {
        return this.mcqType;
    }
    
    public void setMcqType(Integer mcqType) {
        this.mcqType = mcqType;
    }
    public Date getMcqPubTime() {
        return this.mcqPubTime;
    }
    
    public void setMcqPubTime(Date mcqPubTime) {
        this.mcqPubTime = mcqPubTime;
    }




}


