package com.elearing.entity;
// Generated Jun 27, 2015 4:08:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * QuesLevel generated by hbm2java
 */
public class QuesLevel  implements java.io.Serializable {


     private Integer quesLevelId;
     private String quesLevelName;
     private Set examQuesLinks = new HashSet(0);
     private Set mcqQueses = new HashSet(0);

    public QuesLevel() {
    }

	
    public QuesLevel(String quesLevelName) {
        this.quesLevelName = quesLevelName;
    }
    public QuesLevel(String quesLevelName, Set examQuesLinks, Set mcqQueses) {
       this.quesLevelName = quesLevelName;
       this.examQuesLinks = examQuesLinks;
       this.mcqQueses = mcqQueses;
    }
   
    public Integer getQuesLevelId() {
        return this.quesLevelId;
    }
    
    public void setQuesLevelId(Integer quesLevelId) {
        this.quesLevelId = quesLevelId;
    }
    public String getQuesLevelName() {
        return this.quesLevelName;
    }
    
    public void setQuesLevelName(String quesLevelName) {
        this.quesLevelName = quesLevelName;
    }
    public Set getExamQuesLinks() {
        return this.examQuesLinks;
    }
    
    public void setExamQuesLinks(Set examQuesLinks) {
        this.examQuesLinks = examQuesLinks;
    }
    public Set getMcqQueses() {
        return this.mcqQueses;
    }
    
    public void setMcqQueses(Set mcqQueses) {
        this.mcqQueses = mcqQueses;
    }




}


