package com.elearing.entity;
// Generated Jun 27, 2015 4:08:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SubChapter generated by hbm2java
 */
public class SubChapter  implements java.io.Serializable {


     private Integer schId;
     private Subject subject;
     private String schName;
     private String schTopics;
     private String schHints;
     private String subPaper;
     private Set descQueses = new HashSet(0);
     private Set chapterImages = new HashSet(0);
     private Set mcqQueses = new HashSet(0);

    public SubChapter() {
    }

    public SubChapter(Subject subject, String schName, String schTopics, String schHints, String subPaper, Set descQueses, Set chapterImages, Set mcqQueses) {
       this.subject = subject;
       this.schName = schName;
       this.schTopics = schTopics;
       this.schHints = schHints;
       this.subPaper = subPaper;
       this.descQueses = descQueses;
       this.chapterImages = chapterImages;
       this.mcqQueses = mcqQueses;
    }
   
    public Integer getSchId() {
        return this.schId;
    }
    
    public void setSchId(Integer schId) {
        this.schId = schId;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public String getSchName() {
        return this.schName;
    }
    
    public void setSchName(String schName) {
        this.schName = schName;
    }
    public String getSchTopics() {
        return this.schTopics;
    }
    
    public void setSchTopics(String schTopics) {
        this.schTopics = schTopics;
    }
    public String getSchHints() {
        return this.schHints;
    }
    
    public void setSchHints(String schHints) {
        this.schHints = schHints;
    }
    public String getSubPaper() {
        return this.subPaper;
    }
    
    public void setSubPaper(String subPaper) {
        this.subPaper = subPaper;
    }
    public Set getDescQueses() {
        return this.descQueses;
    }
    
    public void setDescQueses(Set descQueses) {
        this.descQueses = descQueses;
    }
    public Set getChapterImages() {
        return this.chapterImages;
    }
    
    public void setChapterImages(Set chapterImages) {
        this.chapterImages = chapterImages;
    }
    public Set getMcqQueses() {
        return this.mcqQueses;
    }
    
    public void setMcqQueses(Set mcqQueses) {
        this.mcqQueses = mcqQueses;
    }




}


