package com.elearing.entity;
// Generated Jun 27, 2015 4:08:38 PM by Hibernate Tools 4.3.1



/**
 * SubEbook generated by hbm2java
 */
public class SubEbook  implements java.io.Serializable {


     private Integer ebookId;
     private Subject subject;
     private String bookLink;

    public SubEbook() {
    }

    public SubEbook(Subject subject, String bookLink) {
       this.subject = subject;
       this.bookLink = bookLink;
    }
   
    public Integer getEbookId() {
        return this.ebookId;
    }
    
    public void setEbookId(Integer ebookId) {
        this.ebookId = ebookId;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public String getBookLink() {
        return this.bookLink;
    }
    
    public void setBookLink(String bookLink) {
        this.bookLink = bookLink;
    }




}


