package com.elearing.entity;
// Generated Jun 27, 2015 4:08:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subject generated by hbm2java
 */
public class Subject  implements java.io.Serializable {


     private Integer subId;
     private ClassInfo classInfo;
     private String subName;
     private String subDesc;
     private String subCode;
     private Set subChapters = new HashSet(0);
     private Set subEbooks = new HashSet(0);
     private Set chapterTypes = new HashSet(0);

    public Subject() {
    }

    public Subject(ClassInfo classInfo, String subName, String subDesc, String subCode, Set subChapters, Set subEbooks, Set chapterTypes) {
       this.classInfo = classInfo;
       this.subName = subName;
       this.subDesc = subDesc;
       this.subCode = subCode;
       this.subChapters = subChapters;
       this.subEbooks = subEbooks;
       this.chapterTypes = chapterTypes;
    }
   
    public Integer getSubId() {
        return this.subId;
    }
    
    public void setSubId(Integer subId) {
        this.subId = subId;
    }
    public ClassInfo getClassInfo() {
        return this.classInfo;
    }
    
    public void setClassInfo(ClassInfo classInfo) {
        this.classInfo = classInfo;
    }
    public String getSubName() {
        return this.subName;
    }
    
    public void setSubName(String subName) {
        this.subName = subName;
    }
    public String getSubDesc() {
        return this.subDesc;
    }
    
    public void setSubDesc(String subDesc) {
        this.subDesc = subDesc;
    }
    public String getSubCode() {
        return this.subCode;
    }
    
    public void setSubCode(String subCode) {
        this.subCode = subCode;
    }
    public Set getSubChapters() {
        return this.subChapters;
    }
    
    public void setSubChapters(Set subChapters) {
        this.subChapters = subChapters;
    }
    public Set getSubEbooks() {
        return this.subEbooks;
    }
    
    public void setSubEbooks(Set subEbooks) {
        this.subEbooks = subEbooks;
    }
    public Set getChapterTypes() {
        return this.chapterTypes;
    }
    
    public void setChapterTypes(Set chapterTypes) {
        this.chapterTypes = chapterTypes;
    }




}


