package com.elearing.entity;
// Generated Jun 27, 2015 4:08:38 PM by Hibernate Tools 4.3.1



/**
 * UserImage generated by hbm2java
 */
public class UserImage  implements java.io.Serializable {


     private Integer imgId;
     private User user;
     private String imageName;
     private String imageUrl;
     private String imageType;
     private String imageSize;

    public UserImage() {
    }

    public UserImage(User user, String imageName, String imageUrl, String imageType, String imageSize) {
       this.user = user;
       this.imageName = imageName;
       this.imageUrl = imageUrl;
       this.imageType = imageType;
       this.imageSize = imageSize;
    }
   
    public Integer getImgId() {
        return this.imgId;
    }
    
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public String getImageType() {
        return this.imageType;
    }
    
    public void setImageType(String imageType) {
        this.imageType = imageType;
    }
    public String getImageSize() {
        return this.imageSize;
    }
    
    public void setImageSize(String imageSize) {
        this.imageSize = imageSize;
    }




}


